### ISSUE TITLE
dbus

### ISSUE THREAD

**Issue by mrgreen3** [hut/minirc#20] opened 2014-05-22 17:39 UTC
I am still having problems with dbus, cannot remember how I got it working. dbus-nosystemd is installed and /run/dbus is present. Really hoping I can get cmst to run in tint2.

**Comment by hut** [comment] 2015-02-11 02:14
Should be fixed since b4bfd2e39a94329d0828af842225dac8971001fd

**Comment by jusplainmike** [comment] 2015-05-17 01:49
So i'm getting operation not permitted errors when trying to use anything tied to dbus. I have dbus-nosystemd installed and @dbus in my minirc.conf. Is there something else i'm missing?

**Comment by mrgreen3** [comment] 2015-05-17 07:08
Can you check if you have anything in /run/dbus? How old is minirc? Last
time I looked it had not been updated in over a year...

**Comment by hut** [comment] 2015-05-17 11:58
dbus works fine for me without dbus-nosystemd. Just fire up the dbus service through minirc with `rc start dbus`. If this doesn't work, can you give me some commands I could run to reproduce your errors?

**Comment by jusplainmike** [comment] 2015-05-17 15:24
Sorry for delay. I will reply with output of rc start dbus. I'm getting the
error when starting wifi-menu on a headless system.

**Comment by jusplainmike** [comment] 2015-05-17 15:28
Currently away from my workbench. Will post reply when I'm back. Thanks for
the help.

**Comment by hut** [comment] 2015-10-16 00:58
I just researched what wifi-menu is, and noticed that it's part of netctl which depends on systemd. That explains why it doesn't work ;)

**Closed by hut** 2015-10-16 00:58 UTC
